version: 2
jobs:
  build:
    docker:
      - image: gopejavi/vokuro-web-example
  test:
    docker:
      - image: gebish/ci:v6
      #- image: gopejavi/vokuro-web-example
    environment:
        GRADLE_OPTS: -Xmx1024m -XX:MaxMetaspaceSize=256m
        GRADLE_USER_HOME: .gradle-home
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-home
      - run:
          command: |
            Xvfb :99 -screen 1 1280x1024x16 -nolisten tcp -fbdir /var/run > /dev/null 2>&1 &
            export DISPLAY=:99
            export FIREFOX_VERSION=56.0.1
            ./gradlew --no-daemon chromeHeadlessTest
      - store_test_results:
          path: build/spock-reports
      - save_cache:
          key: gradle-home
          paths:
            - .gradle-home